services:
  db:
    image: postgres:latest

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_graphql_prisma

    ports:
      - "5432:5432"